apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: elasticsearch 
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate 
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:7.16.2
          name: elasticsearch
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "ES_JAVA_OPTS"
              value: "-Xmx256m -Xms256m"
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              protocol: TCP
              name: port-1
            - containerPort: 9300
              protocol: TCP
              name: port-2
---
apiVersion: v1 
kind: Service 
metadata:
  name: elasticsearch 
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: port-1
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: port-2
  type: LoadBalancer 
  selector:
    app: elasticsearch 






    