apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kibana
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate 
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: kibana:7.16.2
          name: kibana
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5601
              protocol: TCP
              name: kibana-port
          env:
            - name: "ELASTICSEARCH_URL"
              value: "http://elasticsearch:9200"
---
apiVersion: v1 
kind: Service 
metadata:
  name: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: kibana-port
  type: LoadBalancer 
  selector:
    app: kibana