apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: logstash
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate 
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - image: logstash:7.16.2
          name: logstash
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "LS_JAVA_OPTS"
              value: "-Xmx256m -Xms256m"
          ports:
            - containerPort: 9600
              protocol: TCP
              name: log-port
---
apiVersion: v1 
kind: Service 
metadata:
  name: logstash
spec:
  ports:
    - port: 9600
      targetPort: 9600
      protocol: TCP
      name: log-port
  type: LoadBalancer
  selector:
    app: logstash