apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: zipkin
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate 
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - image: openzipkin/zipkin
          name: zipkin
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9411
              protocol: TCP
              name: zipkin-port
---
apiVersion: v1
kind: Service 
metadata: 
  name: zipkin 
spec:
  ports:
    - port: 9411 
      targetPort: 9411 
      protocol: TCP 
      name: zipkin-port 
  type: LoadBalancer 
  selector: 
    app: zipkin 